basePath: /
definitions:
  data.CurrentProject:
    properties:
      id:
        type: integer
      name:
        type: string
      progress:
        type: integer
      tasks:
        items:
          $ref: '#/definitions/data.Task'
        type: array
    type: object
  data.PageInfo:
    properties:
      resultsPerPage:
        type: integer
      totalResults:
        type: integer
    type: object
  data.Post:
    properties:
      content:
        type: string
      date_created:
        type: string
      description:
        type: string
      id:
        type: integer
      image_url:
        type: string
      slug:
        type: string
      title:
        type: string
      type:
        type: string
    type: object
  data.Task:
    properties:
      complete:
        type: boolean
      task:
        type: string
    type: object
  data.Thumbnail:
    properties:
      height:
        type: integer
      url:
        type: string
      width:
        type: integer
    type: object
  data.YouTubeID:
    properties:
      channelId:
        type: string
      kind:
        type: string
      videoId:
        type: string
    type: object
  data.YouTubeItem:
    properties:
      etag:
        type: string
      id:
        $ref: '#/definitions/data.YouTubeID'
      kind:
        type: string
      snippet:
        $ref: '#/definitions/data.YouTubeSnippet'
    type: object
  data.YouTubeResponse:
    properties:
      etag:
        type: string
      items:
        items:
          $ref: '#/definitions/data.YouTubeItem'
        type: array
      kind:
        type: string
      pageInfo:
        $ref: '#/definitions/data.PageInfo'
      regionCode:
        type: string
    type: object
  data.YouTubeSnippet:
    properties:
      channelId:
        type: string
      channelTitle:
        type: string
      description:
        type: string
      liveBroadcastContent:
        type: string
      publishTime:
        type: string
      publishedAt:
        type: string
      thumbnails:
        $ref: '#/definitions/data.YouTubeThumbnails'
      title:
        type: string
    type: object
  data.YouTubeThumbnails:
    properties:
      default:
        $ref: '#/definitions/data.Thumbnail'
      high:
        $ref: '#/definitions/data.Thumbnail'
      medium:
        $ref: '#/definitions/data.Thumbnail'
    type: object
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: Main API for the ProjectXiel website
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: ProjectXiel API
  version: "1.0"
paths:
  /post/{slug}:
    get:
      consumes:
      - application/json
      description: get post by slug
      parameters:
      - description: Post Slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Post'
      summary: Get a single post
      tags:
      - Post
  /posts:
    get:
      consumes:
      - application/json
      description: get current projects
      parameters:
      - description: Projects Limit
        in: query
        name: limit
        type: integer
      - description: Projects page
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.CurrentProject'
      summary: Get all current projects
      tags:
      - Current Project
  /posts/search:
    get:
      consumes:
      - application/json
      description: get posts containing title
      parameters:
      - description: Post title
        in: query
        name: title
        required: true
        type: string
      - description: Posts Limit
        in: query
        name: limit
        type: integer
      - description: Posts page
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Post'
      summary: Search Posts by title
      tags:
      - Post
  /youtube/videos:
    get:
      consumes:
      - application/json
      description: Fetches a list of YouTube videos from a specific channel.
      produces:
      - application/json
      responses:
        "200":
          description: A list of YouTube videos
          schema:
            $ref: '#/definitions/data.YouTubeResponse'
      summary: Fetch YouTube videos
      tags:
      - YouTube
swagger: "2.0"
